import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { TmaSDKLoader } from '../fsd/app/providers/TmaSDKLoader';
import { PropsWithChildren } from 'react';
import ClientProvider from '../fsd/app/providers/ClientProvider';
import '@/fsd/app/styles/global.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<TmaSDKLoader>
					<ClientProvider>{children}</ClientProvider>
				</TmaSDKLoader>
			</body>
		</html>
	);
}
